// Code generated by tokyo-codegen. DO NOT EDIT BY HAND.
// Edit the source API and regenerate instead; hand edits will be overwritten.

#[derive(Debug, clap::Subcommand)]
pub enum EventsCommand {
    ///Watch events [public]
    WatchEvents {},
    ///[public]
    StreamRecords {},
    ///[public]
    CreateChatCompletion {
        #[arg(long = "message")]
        message: String,
        #[arg(long = "stream")]
        stream: Option<bool>,
    },
    ///[public]
    #[command(group(clap::ArgGroup::new("__body_input").required(true).multiple(false)))]
    UploadPresigned {
        upload_url: String,
        /// Read the request body from a file, or from stdin with `-`.
        #[arg(long = "body", value_name = "FILE", group = "__body_input")]
        __body_file: Option<String>,
        /// Supply the request body as inline JSON.
        #[arg(long = "body-json", value_name = "JSON", group = "__body_input")]
        __body_json: Option<String>,
        /// Set a request-body field as `path=value`; repeat for more fields.
        #[arg(
            short = 'f',
            long = "field",
            value_name = "PATH=VALUE",
            group = "__body_input"
        )]
        __body_fields: Vec<String>,
    },
}
pub fn dispatch(
    __command: &EventsCommand,
    __client: &crate::client::Client,
    __output: &crate::output::OutputOptions,
) -> Result<(), crate::error::ClientError> {
    match __command {
        EventsCommand::WatchEvents {} => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = { None };
            let __path = { format!("/events",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            __client
                .request_stream(
                    crate::client::Method::Get,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::None,
                    __request_body,
                    Some("text/event-stream"),
                    None,
                    None,
                    crate::client::StreamKind::Sse,
                    |__payload| {
                        let __value: crate::tokyo::types::Event = serde_json::from_slice(
                                __payload,
                            )
                            .map_err(|error| crate::error::ClientError::Decode(
                                error.to_string(),
                            ))?;
                        crate::output::print_stream_item_as_json_line(&__value)?;
                        Ok(())
                    },
                )?;
            Ok(())
        }
        EventsCommand::StreamRecords {} => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = { None };
            let __path = { format!("/records",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            __client
                .request_stream(
                    crate::client::Method::Get,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::None,
                    __request_body,
                    Some("application/x-ndjson"),
                    None,
                    None,
                    crate::client::StreamKind::Json,
                    |__payload| {
                        let __value: crate::tokyo::types::Event = serde_json::from_slice(
                                __payload,
                            )
                            .map_err(|error| crate::error::ClientError::Decode(
                                error.to_string(),
                            ))?;
                        crate::output::print_stream_item_as_json_line(&__value)?;
                        Ok(())
                    },
                )?;
            Ok(())
        }
        EventsCommand::CreateChatCompletion { message, stream } => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = {
                let __request_value = crate::tokyo::types::ChatRequest {
                    message: message.clone(),
                    stream: stream.clone(),
                };
                Some(
                    crate::client::RequestBody::Json(
                        serde_json::to_vec(&__request_value)
                            .expect("a validated value always serializes"),
                    ),
                )
            };
            let __path = { format!("/chat",) };
            let __target = crate::client::RequestTarget::ServerAndPath {
                server: "https://stream.api.example.test",
                path: &__path,
            };
            if crate::client::json_request_body_field_is_true(
                &__request_body,
                "stream",
            ) {
                __client
                    .request_stream(
                        crate::client::Method::Post,
                        __target,
                        &__query,
                        &__headers,
                        crate::client::AuthMode::None,
                        __request_body,
                        Some("text/event-stream"),
                        Some("application/json"),
                        None,
                        crate::client::StreamKind::Sse,
                        |__payload| {
                            let __value: crate::tokyo::types::ChatChunk = serde_json::from_slice(
                                    __payload,
                                )
                                .map_err(|error| crate::error::ClientError::Decode(
                                    error.to_string(),
                                ))?;
                            crate::output::print_stream_item_as_json_line(&__value)?;
                            Ok(())
                        },
                    )?;
            } else {
                let __response = __client
                    .request(
                        crate::client::Method::Post,
                        __target,
                        &__query,
                        &__headers,
                        crate::client::AuthMode::None,
                        __request_body,
                        Some("application/json"),
                        Some("application/json"),
                        None,
                    )?;
                match __response.status {
                    200u16 => {
                        let __value: crate::tokyo::types::ChatResponse = serde_json::from_slice(
                                &__response.body,
                            )
                            .map_err(|error| crate::error::ClientError::Decode(
                                error.to_string(),
                            ))?;
                        crate::output::print_serialized_response(&__value, __output);
                    }
                    _ => {
                        crate::output::print_untyped_response_body_according_to_content_type(
                            &__response.body,
                            __response.content_type.as_deref(),
                            __output,
                        )?
                    }
                }
            }
            Ok(())
        }
        EventsCommand::UploadPresigned {
            upload_url,
            __body_file,
            __body_json,
            __body_fields,
        } => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = {
                (|| -> Result<
                    Option<crate::client::RequestBody>,
                    crate::error::ClientError,
                > {
                    let __request_json = if let Some(__source) = __body_file.as_deref() {
                        return Ok(
                            Some(
                                crate::client::RequestBody::Binary(
                                    crate::client::read_request_body_bytes(__source)?,
                                ),
                            ),
                        );
                        let __request_text = crate::client::read_request_body_text(
                            __source,
                        )?;
                        serde_json::from_str(&__request_text)
                            .map_err(|error| {
                                crate::error::ClientError::Decode(
                                    format!("invalid JSON in --body {__source:?}: {error}"),
                                )
                            })?
                    } else if let Some(__source) = __body_json.as_deref() {
                        tokyo_cli_runtime::body::parse_inline_json_request_body(
                            __source,
                        )?
                    } else {
                        tokyo_cli_runtime::body::parse_json_request_body_from_field_assignments(
                            __body_fields,
                        )?
                    };
                    let __request_value: String = serde_json::from_value(__request_json)
                        .map_err(|error| crate::error::ClientError::Decode(
                            error.to_string(),
                        ))?;
                    Ok(
                        Some(
                            crate::client::RequestBody::Binary(
                                crate::client::read_request_body_bytes(
                                    &__request_value.to_string(),
                                )?,
                            ),
                        ),
                    )
                })()?
            };
            let __absolute_url = upload_url.to_string();
            let __target = crate::client::RequestTarget::Absolute(&__absolute_url);
            let __response = __client
                .request(
                    crate::client::Method::Put,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::None,
                    __request_body,
                    None,
                    Some("application/octet-stream"),
                    None,
                )?;
            match __response.status {
                204u16 => {}
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
    }
}
pub fn delete_by_id(_id: &str) -> Option<EventsCommand> {
    None
}
