// Code generated by tokyo-codegen. DO NOT EDIT BY HAND.
// Edit the source API and regenerate instead; hand edits will be overwritten.

#[derive(Debug, clap::Subcommand)]
pub enum ItemsCommand {
    #[doc = "List items [public]\n\nReturns documented items safely, even with */ in source prose."]
    ListItems {
        ///Cursor returned by the previous page.
        #[arg(long = "cursor")]
        cursor: Option<String>,
        ///Nested item filters.
        #[arg(long = "filter", value_name = "JSON")]
        filter: Option<String>,
    },
    ///[public]
    #[command(group(clap::ArgGroup::new("__body_input").required(true).multiple(false)))]
    SubmitForm {
        /// Read the request body from a file, or from stdin with `-`.
        #[arg(long = "body", value_name = "FILE", group = "__body_input")]
        __body_file: Option<String>,
        /// Supply the request body as inline JSON.
        #[arg(long = "body-json", value_name = "JSON", group = "__body_input")]
        __body_json: Option<String>,
        /// Set a request-body field as `path=value`; repeat for more fields.
        #[arg(
            short = 'f',
            long = "field",
            value_name = "PATH=VALUE",
            group = "__body_input"
        )]
        __body_fields: Vec<String>,
    },
}
pub fn dispatch(
    __command: &ItemsCommand,
    __client: &crate::client::Client,
    __output: &crate::output::OutputOptions,
) -> Result<(), crate::error::ClientError> {
    match __command {
        ItemsCommand::ListItems { cursor, filter } => {
            let mut __query: Vec<crate::client::QueryParameter> = Vec::new();
            if let Some(value) = &cursor {
                let __parameter_value = serde_json::to_value(value)
                    .expect("a validated parameter always serializes");
                crate::client::append_serialized_parameter_values(
                    &mut __query,
                    "cursor",
                    &__parameter_value,
                    crate::client::ParameterStyle::FormExplode,
                    false,
                );
            }
            if let Some(value) = &filter {
                let __parameter_value = crate::client::parse_json_cli_argument(
                    "filter",
                    value,
                )?;
                crate::client::append_serialized_parameter_values(
                    &mut __query,
                    "filter",
                    &__parameter_value,
                    crate::client::ParameterStyle::DeepObject,
                    false,
                );
            }
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = { None };
            let __path = { format!("/items",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Get,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::None,
                    __request_body,
                    Some("application/json"),
                    None,
                    None,
                )?;
            match __response.status {
                200u16 => {
                    let __value: crate::tokyo::types::ItemPage = serde_json::from_slice(
                            &__response.body,
                        )
                        .map_err(|error| crate::error::ClientError::Decode(
                            error.to_string(),
                        ))?;
                    crate::output::print_serialized_response(&__value, __output);
                }
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
        ItemsCommand::SubmitForm { __body_file, __body_json, __body_fields } => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = {
                (|| -> Result<
                    Option<crate::client::RequestBody>,
                    crate::error::ClientError,
                > {
                    let __request_json = if let Some(__source) = __body_file.as_deref() {
                        let __request_text = crate::client::read_request_body_text(
                            __source,
                        )?;
                        serde_json::from_str(&__request_text)
                            .map_err(|error| {
                                crate::error::ClientError::Decode(
                                    format!("invalid JSON in --body {__source:?}: {error}"),
                                )
                            })?
                    } else if let Some(__source) = __body_json.as_deref() {
                        tokyo_cli_runtime::body::parse_inline_json_request_body(
                            __source,
                        )?
                    } else {
                        tokyo_cli_runtime::body::parse_json_request_body_from_field_assignments(
                            __body_fields,
                        )?
                    };
                    let __request_value: crate::tokyo::types::FormInput = serde_json::from_value(
                            __request_json,
                        )
                        .map_err(|error| crate::error::ClientError::Decode(
                            error.to_string(),
                        ))?;
                    Ok(
                        Some(
                            crate::client::RequestBody::Form(
                                crate::client::build_form_urlencoded_request_body(
                                    serde_json::to_value(&__request_value)
                                        .expect("a validated value always serializes"),
                                    &[],
                                )?,
                            ),
                        ),
                    )
                })()?
            };
            let __path = { format!("/submit",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Post,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::None,
                    __request_body,
                    None,
                    Some("application/x-www-form-urlencoded"),
                    None,
                )?;
            match __response.status {
                204u16 => {}
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
    }
}
pub fn delete_by_id(_id: &str) -> Option<ItemsCommand> {
    None
}
