// Code generated by tokyo-codegen. DO NOT EDIT BY HAND.
// Edit the source API and regenerate instead; hand edits will be overwritten.

#[derive(Debug, clap::Subcommand)]
pub enum ItemsCommand {
    ///[authentication required]
    DeleteItem { item_id: String },
    ///[authentication required]
    #[command(name = "ls", alias = "list")]
    ListItems {
        #[arg(long = "limit")]
        limit: Option<i32>,
        #[arg(long = "q")]
        q: Option<String>,
        #[arg(long = "tag")]
        tag: Option<Vec<String>>,
    },
    ///[authentication required]
    GetItem { #[arg(default_value = "item_123")] item_id: String },
    ///[authentication required]
    CreateItem {
        #[arg(long = "description")]
        description: Option<String>,
        #[arg(long = "name", default_value = "Sample Item")]
        name: String,
    },
}
pub fn dispatch(
    __command: &ItemsCommand,
    __client: &crate::client::Client,
    __output: &crate::output::OutputOptions,
) -> Result<(), crate::error::ClientError> {
    match __command {
        ItemsCommand::DeleteItem { item_id } => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = { None };
            let __path = {
                let value = &item_id;
                let __path_value = serde_json::to_value(value)
                    .expect("a validated parameter always serializes");
                let __path_segment_0 = crate::client::serialize_path_parameter_value(
                    "itemId",
                    &__path_value,
                    crate::client::ParameterStyle::Simple,
                );
                format!("/items/{}", __path_segment_0)
            };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Delete,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::Requirements(
                        &[
                            crate::client::AuthAlternative {
                                schemes: &[
                                    crate::client::AuthScheme {
                                        name: "bearerAuth",
                                        kind: crate::client::AuthSchemeKind::Bearer,
                                        scopes: &[],
                                    },
                                ],
                            },
                        ],
                    ),
                    __request_body,
                    None,
                    None,
                    None,
                )?;
            match __response.status {
                204u16 => {}
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
        ItemsCommand::ListItems { limit, q, tag } => {
            let mut __query: Vec<crate::client::QueryParameter> = Vec::new();
            if let Some(value) = &limit {
                let __parameter_value = serde_json::to_value(value)
                    .expect("a validated parameter always serializes");
                crate::client::append_serialized_parameter_values(
                    &mut __query,
                    "limit",
                    &__parameter_value,
                    crate::client::ParameterStyle::FormExplode,
                    false,
                );
            }
            if let Some(value) = &q {
                let __parameter_value = serde_json::to_value(value)
                    .expect("a validated parameter always serializes");
                crate::client::append_serialized_parameter_values(
                    &mut __query,
                    "q",
                    &__parameter_value,
                    crate::client::ParameterStyle::FormExplode,
                    false,
                );
            }
            if let Some(value) = &tag {
                let __parameter_value = serde_json::to_value(value)
                    .expect("a validated parameter always serializes");
                crate::client::append_serialized_parameter_values(
                    &mut __query,
                    "tag",
                    &__parameter_value,
                    crate::client::ParameterStyle::FormExplode,
                    false,
                );
            }
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = { None };
            let __path = { format!("/items",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Get,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::Requirements(
                        &[
                            crate::client::AuthAlternative {
                                schemes: &[
                                    crate::client::AuthScheme {
                                        name: "bearerAuth",
                                        kind: crate::client::AuthSchemeKind::Bearer,
                                        scopes: &[],
                                    },
                                ],
                            },
                        ],
                    ),
                    __request_body,
                    Some("application/json"),
                    None,
                    None,
                )?;
            match __response.status {
                200u16 => {
                    let __value: Vec<crate::tokyo::types::Item> = serde_json::from_slice(
                            &__response.body,
                        )
                        .map_err(|error| crate::error::ClientError::Decode(
                            error.to_string(),
                        ))?;
                    crate::output::print_serialized_response(&__value, __output);
                }
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
        ItemsCommand::GetItem { item_id } => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = { None };
            let __path = {
                let value = &item_id;
                let __path_value = serde_json::to_value(value)
                    .expect("a validated parameter always serializes");
                let __path_segment_0 = crate::client::serialize_path_parameter_value(
                    "itemId",
                    &__path_value,
                    crate::client::ParameterStyle::Simple,
                );
                format!("/items/{}", __path_segment_0)
            };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Get,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::Requirements(
                        &[
                            crate::client::AuthAlternative {
                                schemes: &[
                                    crate::client::AuthScheme {
                                        name: "bearerAuth",
                                        kind: crate::client::AuthSchemeKind::Bearer,
                                        scopes: &[],
                                    },
                                ],
                            },
                        ],
                    ),
                    __request_body,
                    Some("application/json"),
                    None,
                    Some("application/json"),
                )?;
            match __response.status {
                200u16 => {
                    let __value: crate::tokyo::types::Item = serde_json::from_slice(
                            &__response.body,
                        )
                        .map_err(|error| crate::error::ClientError::Decode(
                            error.to_string(),
                        ))?;
                    crate::output::print_serialized_response(&__value, __output);
                }
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
        ItemsCommand::CreateItem { description, name } => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = {
                let __request_value = crate::tokyo::types::CreateItemRequest {
                    description: description.clone(),
                    name: name.clone(),
                };
                Some(
                    crate::client::RequestBody::Json(
                        serde_json::to_vec(&__request_value)
                            .expect("a validated value always serializes"),
                    ),
                )
            };
            let __path = { format!("/items",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Post,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::Requirements(
                        &[
                            crate::client::AuthAlternative {
                                schemes: &[
                                    crate::client::AuthScheme {
                                        name: "bearerAuth",
                                        kind: crate::client::AuthSchemeKind::Bearer,
                                        scopes: &[],
                                    },
                                ],
                            },
                        ],
                    ),
                    __request_body,
                    Some("application/json"),
                    Some("application/json"),
                    None,
                )?;
            match __response.status {
                200u16 => {
                    let __value: crate::tokyo::types::Item = serde_json::from_slice(
                            &__response.body,
                        )
                        .map_err(|error| crate::error::ClientError::Decode(
                            error.to_string(),
                        ))?;
                    if let Ok(__created_json) = serde_json::to_value(&__value) {
                        if let Some(__created_id) = __created_json.get("id") {
                            crate::session::append_created_resource_to_session_reset_log(
                                "items",
                                __created_id,
                            );
                        }
                    }
                    crate::output::print_serialized_response(&__value, __output);
                }
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
    }
}
pub fn delete_by_id(__id: &str) -> Option<ItemsCommand> {
    Some(ItemsCommand::DeleteItem {
        item_id: __id.parse().ok()?,
    })
}
