// Code generated by tokyo-codegen. DO NOT EDIT BY HAND.
// Edit the source API and regenerate instead; hand edits will be overwritten.

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Message {
    pub message: String,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Problem {
    pub code: String,
    pub message: String,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReplaceMultipartRequest {
    pub file: String,
}
