// Code generated by tokyo-codegen. DO NOT EDIT BY HAND.
// Edit the source API and regenerate instead; hand edits will be overwritten.

#[derive(Debug, clap::Subcommand)]
pub enum DefaultCommand {
    ///[authentication required]
    AlternativeAuth {},
    ///[authentication required]
    CombinedAuth {},
    ///[authentication required]
    InheritedAuth {},
    ///[authentication required]
    InteractiveAuth {},
    ///[authentication required]
    MachineAuth {},
    ///[authentication optional]
    OptionalAuth {},
    ///[public]
    PublicOperation {},
    ///[authentication required]
    RelativeMachineAuth {},
}
pub fn dispatch(
    __command: &DefaultCommand,
    __client: &crate::client::Client,
    __output: &crate::output::OutputOptions,
) -> Result<(), crate::error::ClientError> {
    match __command {
        DefaultCommand::AlternativeAuth {} => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = { None };
            let __path = { format!("/alternative",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Get,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::Requirements(
                        &[
                            crate::client::AuthAlternative {
                                schemes: &[
                                    crate::client::AuthScheme {
                                        name: "basicAuth",
                                        kind: crate::client::AuthSchemeKind::Basic,
                                        scopes: &[],
                                    },
                                ],
                            },
                            crate::client::AuthAlternative {
                                schemes: &[
                                    crate::client::AuthScheme {
                                        name: "bearerAuth",
                                        kind: crate::client::AuthSchemeKind::Bearer,
                                        scopes: &[],
                                    },
                                ],
                            },
                        ],
                    ),
                    __request_body,
                    None,
                    None,
                    None,
                )?;
            match __response.status {
                204u16 => {}
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
        DefaultCommand::CombinedAuth {} => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = { None };
            let __path = { format!("/combined",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Get,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::Requirements(
                        &[
                            crate::client::AuthAlternative {
                                schemes: &[
                                    crate::client::AuthScheme {
                                        name: "primaryKey",
                                        kind: crate::client::AuthSchemeKind::Header(
                                            "X-Primary-Key",
                                        ),
                                        scopes: &[],
                                    },
                                    crate::client::AuthScheme {
                                        name: "secondaryKey",
                                        kind: crate::client::AuthSchemeKind::Header(
                                            "X-Secondary-Key",
                                        ),
                                        scopes: &[],
                                    },
                                    crate::client::AuthScheme {
                                        name: "sessionCookie",
                                        kind: crate::client::AuthSchemeKind::CookieKey(
                                            "session_id",
                                        ),
                                        scopes: &[],
                                    },
                                ],
                            },
                        ],
                    ),
                    __request_body,
                    None,
                    None,
                    None,
                )?;
            match __response.status {
                204u16 => {}
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
        DefaultCommand::InheritedAuth {} => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = { None };
            let __path = { format!("/inherited",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Get,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::Requirements(
                        &[
                            crate::client::AuthAlternative {
                                schemes: &[
                                    crate::client::AuthScheme {
                                        name: "primaryKey",
                                        kind: crate::client::AuthSchemeKind::Header(
                                            "X-Primary-Key",
                                        ),
                                        scopes: &[],
                                    },
                                ],
                            },
                        ],
                    ),
                    __request_body,
                    None,
                    None,
                    None,
                )?;
            match __response.status {
                204u16 => {}
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
        DefaultCommand::InteractiveAuth {} => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = { None };
            let __path = { format!("/interactive",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Get,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::Requirements(
                        &[
                            crate::client::AuthAlternative {
                                schemes: &[
                                    crate::client::AuthScheme {
                                        name: "interactiveOAuth",
                                        kind: crate::client::AuthSchemeKind::OAuth2Bearer,
                                        scopes: &["profile"],
                                    },
                                ],
                            },
                        ],
                    ),
                    __request_body,
                    None,
                    None,
                    None,
                )?;
            match __response.status {
                204u16 => {}
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
        DefaultCommand::MachineAuth {} => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = { None };
            let __path = { format!("/machine",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Get,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::Requirements(
                        &[
                            crate::client::AuthAlternative {
                                schemes: &[
                                    crate::client::AuthScheme {
                                        name: "machineOAuth",
                                        kind: crate::client::AuthSchemeKind::OAuth2ClientCredentials(
                                            "https://identity.example.test/oauth/token",
                                        ),
                                        scopes: &["read"],
                                    },
                                ],
                            },
                        ],
                    ),
                    __request_body,
                    None,
                    None,
                    None,
                )?;
            match __response.status {
                204u16 => {}
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
        DefaultCommand::OptionalAuth {} => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = { None };
            let __path = { format!("/optional",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Get,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::Requirements(
                        &[
                            crate::client::AuthAlternative {
                                schemes: &[
                                    crate::client::AuthScheme {
                                        name: "bearerAuth",
                                        kind: crate::client::AuthSchemeKind::Bearer,
                                        scopes: &[],
                                    },
                                ],
                            },
                            crate::client::AuthAlternative {
                                schemes: &[],
                            },
                        ],
                    ),
                    __request_body,
                    None,
                    None,
                    None,
                )?;
            match __response.status {
                204u16 => {}
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
        DefaultCommand::PublicOperation {} => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = { None };
            let __path = { format!("/public",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Get,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::None,
                    __request_body,
                    None,
                    None,
                    None,
                )?;
            match __response.status {
                204u16 => {}
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
        DefaultCommand::RelativeMachineAuth {} => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = { None };
            let __path = { format!("/relative-machine",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Get,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::Requirements(
                        &[
                            crate::client::AuthAlternative {
                                schemes: &[
                                    crate::client::AuthScheme {
                                        name: "relativeMachineOAuth",
                                        kind: crate::client::AuthSchemeKind::OAuth2ClientCredentials(
                                            "/oauth/relative-token",
                                        ),
                                        scopes: &["read"],
                                    },
                                ],
                            },
                        ],
                    ),
                    __request_body,
                    None,
                    None,
                    None,
                )?;
            match __response.status {
                204u16 => {}
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
    }
}
pub fn delete_by_id(_id: &str) -> Option<DefaultCommand> {
    None
}
