// Code generated by tokyo-codegen. DO NOT EDIT BY HAND.
// Edit the source API and regenerate instead; hand edits will be overwritten.

#[derive(Debug, clap::Subcommand)]
pub enum EventsCommand {
    ///[public]
    GetEvent {
        event_id: uuid::Uuid,
        #[arg(long = "since")]
        since: Option<chrono::DateTime<chrono::Utc>>,
        #[arg(long = "X-Report-Date")]
        x_report_date: Option<chrono::NaiveDate>,
    },
    ///[public]
    CreateEvent {
        #[arg(long = "id")]
        id: uuid::Uuid,
        #[arg(long = "localDate")]
        local_date: chrono::NaiveDate,
        #[arg(long = "occurredAt")]
        occurred_at: chrono::DateTime<chrono::Utc>,
    },
}
pub fn dispatch(
    __command: &EventsCommand,
    __client: &crate::client::Client,
    __output: &crate::output::OutputOptions,
) -> Result<(), crate::error::ClientError> {
    match __command {
        EventsCommand::GetEvent { event_id, since, x_report_date } => {
            let mut __query: Vec<crate::client::QueryParameter> = Vec::new();
            if let Some(value) = &since {
                let __parameter_value = serde_json::to_value(value)
                    .expect("a validated parameter always serializes");
                crate::client::append_serialized_parameter_values(
                    &mut __query,
                    "since",
                    &__parameter_value,
                    crate::client::ParameterStyle::FormExplode,
                    false,
                );
            }
            let mut __headers: Vec<(String, String)> = Vec::new();
            if let Some(value) = &x_report_date {
                let __parameter_value = serde_json::to_value(value)
                    .expect("a validated parameter always serializes");
                let __parameter_value = crate::client::serialize_header_parameter_value(
                    &__parameter_value,
                    crate::client::ParameterStyle::Simple,
                );
                __headers.push(("X-Report-Date".to_string(), __parameter_value));
            }
            let __request_body = { None };
            let __path = {
                let value = &event_id;
                let __path_value = serde_json::to_value(value)
                    .expect("a validated parameter always serializes");
                let __path_segment_0 = crate::client::serialize_path_parameter_value(
                    "eventId",
                    &__path_value,
                    crate::client::ParameterStyle::Simple,
                );
                format!("/events/{}", __path_segment_0)
            };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Get,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::None,
                    __request_body,
                    Some("application/json"),
                    None,
                    None,
                )?;
            match __response.status {
                200u16 => {
                    let __value: crate::tokyo::types::Event = serde_json::from_slice(
                            &__response.body,
                        )
                        .map_err(|error| crate::error::ClientError::Decode(
                            error.to_string(),
                        ))?;
                    crate::output::print_serialized_response(&__value, __output);
                }
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
        EventsCommand::CreateEvent { id, local_date, occurred_at } => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = {
                let __request_value = crate::tokyo::types::Event {
                    id: id.clone(),
                    local_date: local_date.clone(),
                    occurred_at: occurred_at.clone(),
                };
                Some(
                    crate::client::RequestBody::Json(
                        serde_json::to_vec(&__request_value)
                            .expect("a validated value always serializes"),
                    ),
                )
            };
            let __path = { format!("/events",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Post,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::None,
                    __request_body,
                    Some("application/json"),
                    Some("application/json"),
                    None,
                )?;
            match __response.status {
                200u16 => {
                    let __value: crate::tokyo::types::Event = serde_json::from_slice(
                            &__response.body,
                        )
                        .map_err(|error| crate::error::ClientError::Decode(
                            error.to_string(),
                        ))?;
                    if let Ok(__created_json) = serde_json::to_value(&__value) {
                        if let Some(__created_id) = __created_json.get("id") {
                            crate::session::append_created_resource_to_session_reset_log(
                                "events",
                                __created_id,
                            );
                        }
                    }
                    crate::output::print_serialized_response(&__value, __output);
                }
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
    }
}
pub fn delete_by_id(_id: &str) -> Option<EventsCommand> {
    None
}
