// Code generated by tokyo-codegen. DO NOT EDIT BY HAND.
// Edit the source API and regenerate instead; hand edits will be overwritten.

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Company {
    #[serde(rename = "companyName")]
    pub company_name: String,
    pub kind: String,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreatePetRequest {
    pub name: String,
    pub tag: Option<String>,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Error {
    pub message: String,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(untagged)]
pub enum Owner {
    OwnerVariant1(crate::tokyo::types::Company),
    OwnerVariant0(crate::tokyo::types::Person),
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Person {
    #[serde(rename = "fullName")]
    pub full_name: String,
    pub kind: String,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Pet {
    pub id: i64,
    pub name: String,
    pub status: crate::tokyo::types::PetStatus,
    pub tag: Option<String>,
}
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    serde::Serialize,
    serde::Deserialize,
    clap::ValueEnum
)]
pub enum PetStatus {
    #[serde(rename = "available")]
    #[value(name = "available")]
    Available,
    #[serde(rename = "pending")]
    #[value(name = "pending")]
    Pending,
    #[serde(rename = "sold")]
    #[value(name = "sold")]
    Sold,
}
impl std::fmt::Display for PetStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(
            match self {
                PetStatus::Available => "available",
                PetStatus::Pending => "pending",
                PetStatus::Sold => "sold",
            },
        )
    }
}
