//! Shared runtime for API command-line clients generated by Tokyo.
//!
//! Generated crates provide their API-specific command tree, models, and
//! configuration while this crate owns transport, authentication, profiles,
//! output, and session behavior.

#![forbid(unsafe_code)]

pub mod achieve;
pub mod body;
/// HTTP client, request serialization, and response buffering.
pub mod client;
/// Generated CLI runtime configuration.
pub mod config;
/// Error reporting for generated commands.
pub mod error;
/// OAuth login, token storage, refresh, and diagnostics.
pub mod oauth;
/// Human and machine-readable output rendering.
pub mod output;
/// Credential and connection-profile storage.
pub mod profile;
/// Route-first API for handwritten CLI commands.
pub mod route;
/// Scenario parsing and execution helpers.
pub mod scenario;
pub mod schema;
/// Per-process session state used by scenarios and generated commands.
pub mod session;
/// Background self-update against GitHub Releases.
pub mod update;

pub use config::{
    CliScenario, ProductIdentity, RuntimeConfig, UpdateConfig, configure_generated_cli_runtime,
};

/// Common imports for handwritten route modules.
pub mod prelude {
    pub use crate::client::{AuthMode, Method, RequestBody, RequestTarget};
    pub use crate::error::ClientError;
    pub use crate::output::{OutputFormat, OutputOptions};
    pub use crate::route::{
        Argument, AuthPolicy, HttpRequestBuilder, Middleware, MiddlewareNext, Route, RouteArgs,
        RouteContext, RouteResponse, RouteResult, RouteRunError, RouteSpec,
    };
}
