// Code generated by tokyo-codegen. DO NOT EDIT BY HAND.
// Edit the source API and regenerate instead; hand edits will be overwritten.

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Event {
    pub id: uuid::Uuid,
    #[serde(rename = "localDate")]
    pub local_date: chrono::NaiveDate,
    #[serde(rename = "occurredAt")]
    pub occurred_at: chrono::DateTime<chrono::Utc>,
}
