// Code generated by tokyo-codegen. DO NOT EDIT BY HAND.
// Edit the source API and regenerate instead; hand edits will be overwritten.

#[derive(Debug, clap::Subcommand)]
pub enum UsersCommand {
    ///[authentication required]
    ListUserNotes {
        user_id: String,
        #[arg(long = "X-Trace-Id")]
        x_trace_id: Option<String>,
    },
    ///[authentication required]
    #[command(hide = true)]
    #[command(group(clap::ArgGroup::new("__body_input").required(true).multiple(false)))]
    CreateUser {
        /// Read the request body from a file, or from stdin with `-`.
        #[arg(long = "body", value_name = "FILE", group = "__body_input")]
        __body_file: Option<String>,
        /// Supply the request body as inline JSON.
        #[arg(long = "body-json", value_name = "JSON", group = "__body_input")]
        __body_json: Option<String>,
        /// Set a request-body field as `path=value`; repeat for more fields.
        #[arg(
            short = 'f',
            long = "field",
            value_name = "PATH=VALUE",
            group = "__body_input"
        )]
        __body_fields: Vec<String>,
    },
}
pub fn dispatch(
    __command: &UsersCommand,
    __client: &crate::client::Client,
    __output: &crate::output::OutputOptions,
) -> Result<(), crate::error::ClientError> {
    match __command {
        UsersCommand::ListUserNotes { user_id, x_trace_id } => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let mut __headers: Vec<(String, String)> = Vec::new();
            if let Some(value) = &x_trace_id {
                let __parameter_value = serde_json::to_value(value)
                    .expect("a validated parameter always serializes");
                let __parameter_value = crate::client::serialize_header_parameter_value(
                    &__parameter_value,
                    crate::client::ParameterStyle::Simple,
                );
                __headers.push(("X-Trace-Id".to_string(), __parameter_value));
            }
            let __request_body = { None };
            let __path = {
                let value = &user_id;
                let __path_value = serde_json::to_value(value)
                    .expect("a validated parameter always serializes");
                let __path_segment_0 = crate::client::serialize_path_parameter_value(
                    "userId",
                    &__path_value,
                    crate::client::ParameterStyle::Simple,
                );
                format!("/users/{}/notes", __path_segment_0)
            };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Get,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::Requirements(
                        &[
                            crate::client::AuthAlternative {
                                schemes: &[
                                    crate::client::AuthScheme {
                                        name: "bearerAuth",
                                        kind: crate::client::AuthSchemeKind::Bearer,
                                        scopes: &[],
                                    },
                                ],
                            },
                        ],
                    ),
                    __request_body,
                    Some("application/json"),
                    None,
                    None,
                )?;
            match __response.status {
                200u16 => {
                    let __value: Vec<crate::tokyo::types::Note> = serde_json::from_slice(
                            &__response.body,
                        )
                        .map_err(|error| crate::error::ClientError::Decode(
                            error.to_string(),
                        ))?;
                    crate::output::print_serialized_response(&__value, __output);
                }
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
        UsersCommand::CreateUser { __body_file, __body_json, __body_fields } => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = {
                (|| -> Result<
                    Option<crate::client::RequestBody>,
                    crate::error::ClientError,
                > {
                    let __request_json = if let Some(__source) = __body_file.as_deref() {
                        let __request_text = crate::client::read_request_body_text(
                            __source,
                        )?;
                        serde_json::from_str(&__request_text)
                            .map_err(|error| {
                                crate::error::ClientError::Decode(
                                    format!("invalid JSON in --body {__source:?}: {error}"),
                                )
                            })?
                    } else if let Some(__source) = __body_json.as_deref() {
                        tokyo_cli_runtime::body::parse_inline_json_request_body(
                            __source,
                        )?
                    } else {
                        tokyo_cli_runtime::body::parse_json_request_body_from_field_assignments(
                            __body_fields,
                        )?
                    };
                    let __request_value: crate::tokyo::types::CreateUserRequest = serde_json::from_value(
                            __request_json,
                        )
                        .map_err(|error| crate::error::ClientError::Decode(
                            error.to_string(),
                        ))?;
                    Ok(
                        Some(
                            crate::client::RequestBody::Json(
                                serde_json::to_vec(&__request_value)
                                    .expect("a validated value always serializes"),
                            ),
                        ),
                    )
                })()?
            };
            let __path = { format!("/users",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Post,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::Requirements(
                        &[
                            crate::client::AuthAlternative {
                                schemes: &[
                                    crate::client::AuthScheme {
                                        name: "bearerAuth",
                                        kind: crate::client::AuthSchemeKind::Bearer,
                                        scopes: &[],
                                    },
                                ],
                            },
                        ],
                    ),
                    __request_body,
                    Some("application/json"),
                    Some("application/json"),
                    None,
                )?;
            match __response.status {
                200u16 => {
                    let __value: crate::tokyo::types::User = serde_json::from_slice(
                            &__response.body,
                        )
                        .map_err(|error| crate::error::ClientError::Decode(
                            error.to_string(),
                        ))?;
                    if let Ok(__created_json) = serde_json::to_value(&__value) {
                        if let Some(__created_id) = __created_json.get("id") {
                            crate::session::append_created_resource_to_session_reset_log(
                                "users",
                                __created_id,
                            );
                        }
                    }
                    crate::output::print_serialized_response(&__value, __output);
                }
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
    }
}
pub fn delete_by_id(_id: &str) -> Option<UsersCommand> {
    None
}
