// Code generated by tokyo-codegen. DO NOT EDIT BY HAND.
// Edit the source API and regenerate instead; hand edits will be overwritten.

pub const CONFIG: tokyo_cli_runtime::RuntimeConfig = tokyo_cli_runtime::RuntimeConfig {
    identity: tokyo_cli_runtime::ProductIdentity {
        package_name: "generated-cli",
        command_name: "generated-cli",
        env_prefix: "GENERATED_CLI",
    },
    default_base_url: Some("https://us.api.example.test/v1"),
    environments: &[],
    oauth_providers: &[],
    scenarios: &[],
};
