// Code generated by tokyo-codegen. DO NOT EDIT BY HAND.
// Edit the source API and regenerate instead; hand edits will be overwritten.

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct UploadRequest {
    #[serde(rename = "display-name")]
    pub display_name: String,
    pub file: String,
    pub metadata: crate::tokyo::types::UploadRequestMetadata,
    pub tags: Vec<String>,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct UploadRequestMetadata {
    #[serde(rename = "source-name")]
    pub source_name: String,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct WirePayload {
    #[serde(rename = "display-name")]
    pub display_name: String,
    #[serde(rename = "nested-value")]
    pub nested_value: crate::tokyo::types::WirePayloadNestedValue,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct WirePayloadNestedValue {
    #[serde(rename = "inner-key")]
    pub inner_key: String,
}
