// Code generated by tokyo-codegen. DO NOT EDIT BY HAND.
// Edit the source API and regenerate instead; hand edits will be overwritten.

pub fn augment(command: clap::Command) -> clap::Command { command }
pub fn dispatch(
_matches: &clap::ArgMatches,
_context: &crate::cli::CommandContext<'_>,
) -> Result<bool, crate::error::ClientError> { Ok(false) }
pub fn metadata() -> serde_json::Value { serde_json::json!([]) }
