// Code generated by tokyo-codegen. DO NOT EDIT BY HAND.
// Edit the source API and regenerate instead; hand edits will be overwritten.

/// A field that may be present-and-null, distinct from `Option`'s
/// absent/present. Composes with `Option<Nullable<T>>` for fields that can
/// be absent, null, or a value (JSON's actual three-state shape).
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(untagged)]
pub enum Nullable<T> {
    Null,
    Value(T),
}
impl<T> From<Option<T>> for Nullable<T> {
    fn from(value: Option<T>) -> Self {
        match value {
            Some(value) => Nullable::Value(value),
            None => Nullable::Null,
        }
    }
}
impl<T> From<Nullable<T>> for Option<T> {
    fn from(value: Nullable<T>) -> Self {
        match value {
            Nullable::Value(value) => Some(value),
            Nullable::Null => None,
        }
    }
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ChatChunk {
    pub delta: String,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ChatRequest {
    pub message: String,
    pub stream: Option<bool>,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ChatResponse {
    pub message: String,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Event {
    pub id: String,
    pub payload: Option<std::collections::BTreeMap<String, serde_json::Value>>,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct FormInput {
    pub name: String,
    pub tags: Option<Vec<String>>,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Item {
    pub id: String,
    pub labels: crate::tokyo::types::Labels,
    pub status: crate::tokyo::types::Status,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ItemPage {
    pub items: Vec<crate::tokyo::types::Item>,
    #[serde(rename = "nextCursor")]
    pub next_cursor: Option<crate::tokyo::types::Nullable<String>>,
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Labels {}
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    serde::Serialize,
    serde::Deserialize,
    clap::ValueEnum
)]
pub enum Status {
    #[serde(rename = "active")]
    #[value(name = "active")]
    Active,
    #[serde(rename = "paused")]
    #[value(name = "paused")]
    Paused,
    #[serde(other)]
    #[value(name = "unknown")]
    Unknown,
}
impl std::fmt::Display for Status {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(
            match self {
                Status::Active => "active",
                Status::Paused => "paused",
                Status::Unknown => "unknown",
            },
        )
    }
}
