// Code generated by tokyo-codegen. DO NOT EDIT BY HAND.
// Edit the source API and regenerate instead; hand edits will be overwritten.

pub const CONFIG: tokyo_cli_runtime::RuntimeConfig = tokyo_cli_runtime::RuntimeConfig {
    identity: tokyo_cli_runtime::ProductIdentity {
        package_name: "generated-cli",
        command_name: "generated-cli",
        env_prefix: "GENERATED_CLI",
    },
    default_base_url: None,
    environments: &[],
    oauth_providers: &[
        tokyo_cli_runtime::oauth::OAuthProvider {
            scheme: "bearerAuth",
            client_id: "golden-public-client",
            redirect_uri: None,
            endpoints: tokyo_cli_runtime::oauth::OAuthEndpoints::Explicit {
                authorization_url: Some("https://identity.example.test/authorize"),
                token_url: "https://identity.example.test/token",
                device_authorization_url: Some("https://identity.example.test/device"),
            },
            scopes: &["openid", "offline_access"],
            audience: Some("https://api.example.test"),
        },
    ],
    scenarios: &[],
    update: None,
};
