// Code generated by tokyo-codegen. DO NOT EDIT BY HAND.
// Edit the source API and regenerate instead; hand edits will be overwritten.

#[derive(Debug, clap::Subcommand)]
pub enum DefaultCommand {
    ///[authentication required]
    ListPets {},
    ///[authentication required]
    GetPet { pet_id: i64 },
    ///[authentication required]
    CreatePet {
        #[arg(long = "name")]
        name: String,
        #[arg(long = "tag")]
        tag: Option<String>,
    },
}
pub fn dispatch(
    __command: &DefaultCommand,
    __client: &crate::client::Client,
    __output: &crate::output::OutputOptions,
) -> Result<(), crate::error::ClientError> {
    match __command {
        DefaultCommand::ListPets {} => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = { None };
            let __path = { format!("/pets",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Get,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::Requirements(
                        &[
                            crate::client::AuthAlternative {
                                schemes: &[
                                    crate::client::AuthScheme {
                                        name: "bearerAuth",
                                        kind: crate::client::AuthSchemeKind::Bearer,
                                        scopes: &[],
                                    },
                                ],
                            },
                        ],
                    ),
                    __request_body,
                    Some("application/json"),
                    None,
                    None,
                )?;
            match __response.status {
                200u16 => {
                    let __value: Vec<crate::tokyo::types::Pet> = serde_json::from_slice(
                            &__response.body,
                        )
                        .map_err(|error| crate::error::ClientError::Decode(
                            error.to_string(),
                        ))?;
                    crate::output::print_serialized_response(&__value, __output);
                }
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
        DefaultCommand::GetPet { pet_id } => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = { None };
            let __path = {
                let value = &pet_id;
                let __path_value = serde_json::to_value(value)
                    .expect("a validated parameter always serializes");
                let __path_segment_0 = crate::client::serialize_path_parameter_value(
                    "petId",
                    &__path_value,
                    crate::client::ParameterStyle::Simple,
                );
                format!("/pets/{}", __path_segment_0)
            };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Get,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::Requirements(
                        &[
                            crate::client::AuthAlternative {
                                schemes: &[
                                    crate::client::AuthScheme {
                                        name: "bearerAuth",
                                        kind: crate::client::AuthSchemeKind::Bearer,
                                        scopes: &[],
                                    },
                                ],
                            },
                        ],
                    ),
                    __request_body,
                    Some("application/json"),
                    None,
                    Some("application/json"),
                )?;
            match __response.status {
                200u16 => {
                    let __value: crate::tokyo::types::Pet = serde_json::from_slice(
                            &__response.body,
                        )
                        .map_err(|error| crate::error::ClientError::Decode(
                            error.to_string(),
                        ))?;
                    crate::output::print_serialized_response(&__value, __output);
                }
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
        DefaultCommand::CreatePet { name, tag } => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = {
                let __request_value = crate::tokyo::types::CreatePetRequest {
                    name: name.clone(),
                    tag: tag.clone(),
                };
                Some(
                    crate::client::RequestBody::Json(
                        serde_json::to_vec(&__request_value)
                            .expect("a validated value always serializes"),
                    ),
                )
            };
            let __path = { format!("/pets",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Post,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::Requirements(
                        &[
                            crate::client::AuthAlternative {
                                schemes: &[
                                    crate::client::AuthScheme {
                                        name: "bearerAuth",
                                        kind: crate::client::AuthSchemeKind::Bearer,
                                        scopes: &[],
                                    },
                                ],
                            },
                        ],
                    ),
                    __request_body,
                    Some("application/json"),
                    Some("application/json"),
                    None,
                )?;
            match __response.status {
                200u16 => {
                    let __value: crate::tokyo::types::Pet = serde_json::from_slice(
                            &__response.body,
                        )
                        .map_err(|error| crate::error::ClientError::Decode(
                            error.to_string(),
                        ))?;
                    if let Ok(__created_json) = serde_json::to_value(&__value) {
                        if let Some(__created_id) = __created_json.get("id") {
                            crate::session::append_created_resource_to_session_reset_log(
                                "default",
                                __created_id,
                            );
                        }
                    }
                    crate::output::print_serialized_response(&__value, __output);
                }
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
    }
}
pub fn delete_by_id(_id: &str) -> Option<DefaultCommand> {
    None
}
