//! Emitter that renders a Tokyo IR API as a standalone Rust CLI project.
//!
//! The emitter owns source generation only. It receives an in-memory IR value
//! and returns deterministic file paths and contents for a front end to write.

mod commands;
mod naming;
mod schema;
mod templates;
mod types;

pub(crate) use types::{RenderOptions, TypeCatalog};

use heck::ToKebabCase;
pub use tokyo_codegen_engine::GeneratedFile;
use tokyo_ir::Api;

/// `emit-cli`-generated types double as CLI arg/flag values, so enums derive
/// `clap::ValueEnum` alongside the usual serde derives.
const RENDER_OPTIONS: RenderOptions = RenderOptions {
    derive_clap_value_enum: true,
};

const GENERATED_HEADER: &str = "// Code generated by tokyo-codegen. DO NOT EDIT BY HAND.\n// Edit the source API and regenerate instead; hand edits will be overwritten.\n\n";

/// Developer-owned files emitted only as an initial scaffold: front ends must
/// never overwrite them once they exist and must exclude them from the
/// managed-file manifest.
pub const UNMANAGED_STARTER_FILES: &[&str] = &[
    "Cargo.toml",
    "README.md",
    ".cursor/skills/tokyo-achieve-outcomes/SKILL.md",
    ".cursor/skills/tokyo-agent-discovery/SKILL.md",
    ".cursor/skills/tokyo-auth-profiles/SKILL.md",
    ".cursor/skills/tokyo-filesystem-routes/SKILL.md",
    ".cursor/skills/tokyo-guidance-presentation/SKILL.md",
    ".cursor/skills/tokyo-openapi-lifecycle/SKILL.md",
    ".cursor/skills/tokyo-project-config/SKILL.md",
    ".cursor/skills/tokyo-project-layout/SKILL.md",
    ".cursor/skills/tokyo-request-bodies/SKILL.md",
    ".cursor/skills/tokyo-scenarios-run/SKILL.md",
    ".cursor/skills/tokyo-scripting-protocol/SKILL.md",
    ".cursor/skills/tokyo-streaming-binary/SKILL.md",
    "src/commands/mod.rs",
    "src/commands/custom.rs",
    "src/commands/guidance.rs",
    "src/middleware.rs",
    "src/presentation.rs",
];

/// Builds the developer-owned Cursor skills installed into a Tokyo project.
#[must_use = "callers must write or compare the starter files"]
pub fn project_skill_starter_files() -> Vec<GeneratedFile> {
    templates::project_skill_starter_files()
}

/// Builds every generated file for a CLI project from an API IR snapshot.
#[must_use = "callers must write or compare the generated files"]
pub fn emit_generated_cli_project_files(api: &Api) -> Vec<GeneratedFile> {
    let mut api = api.clone();
    api.canonicalize();

    let catalog = TypeCatalog::new(&api.types);
    let configured_name = api
        .cli
        .cli_name
        .clone()
        .or_else(|| api.cli.package_name.clone())
        .unwrap_or_else(|| "generated-cli".to_string());
    let names = naming::derive_package_and_command_names(&configured_name);
    let command_name = names.command;

    let mut files = vec![
        GeneratedFile {
            relative_path: "Cargo.toml".to_string(),
            contents: templates::render_generated_cli_cargo_manifest_source_file(
                &names.cargo_package,
            ),
        },
        GeneratedFile {
            relative_path: "README.md".to_string(),
            contents: templates::render_generated_cli_readme_source_file(&command_name, &api.cli),
        },
        GeneratedFile {
            relative_path: ".tokyo/src/main.rs".to_string(),
            contents: format!("{GENERATED_HEADER}{}", templates::MAIN_RS),
        },
        GeneratedFile {
            relative_path: ".tokyo/src/tokyo/mod.rs".to_string(),
            contents: format!(
                "{GENERATED_HEADER}pub mod commands;\npub mod config;\npub mod routes;\npub mod types;\n"
            ),
        },
        GeneratedFile {
            relative_path: ".tokyo/src/tokyo/config.rs".to_string(),
            contents: format_generated_rust_source(
                &templates::render_generated_cli_runtime_config_source_file(
                    &api.cli,
                    &names.cargo_package,
                    &command_name,
                ),
            ),
        },
        GeneratedFile {
            relative_path: ".tokyo/src/tokyo/routes.rs".to_string(),
            contents: format!(
                "{GENERATED_HEADER}\
                 pub fn augment(command: clap::Command) -> clap::Command {{ command }}\n\
                 pub fn dispatch(\n\
                     _matches: &clap::ArgMatches,\n\
                     _context: &crate::cli::CommandContext<'_>,\n\
                 ) -> Result<bool, crate::error::ClientError> {{ Ok(false) }}\n\
                 pub fn metadata() -> serde_json::Value {{ serde_json::json!([]) }}\n"
            ),
        },
        GeneratedFile {
            relative_path: ".tokyo/src/tokyo/types.rs".to_string(),
            contents: render_rust_file_from_tokens(render_generated_type_tokens(&api, &catalog)),
        },
        GeneratedFile {
            relative_path: "src/commands/mod.rs".to_string(),
            contents: templates::COMMANDS_MOD_RS.to_string(),
        },
        GeneratedFile {
            relative_path: "src/commands/custom.rs".to_string(),
            contents: templates::CUSTOM_RS.to_string(),
        },
        GeneratedFile {
            relative_path: "src/commands/guidance.rs".to_string(),
            contents: templates::GUIDANCE_RS.to_string(),
        },
        GeneratedFile {
            relative_path: "src/middleware.rs".to_string(),
            contents: templates::MIDDLEWARE_RS.to_string(),
        },
        GeneratedFile {
            relative_path: "src/presentation.rs".to_string(),
            contents: templates::PRESENTATION_RS.to_string(),
        },
    ];
    files.extend(project_skill_starter_files());

    let mut groups = commands::resource_groups(&api.endpoints);
    for dispatch in &api.cli.cli_dispatch_groups {
        if !groups
            .iter()
            .any(|(tag, _)| tag.to_kebab_case() == dispatch.resource.to_kebab_case())
        {
            groups.push((dispatch.resource.clone(), Vec::new()));
        }
    }
    groups.sort_by(|left, right| left.0.cmp(&right.0));
    let resources = commands::resolve_resource_names(&groups);
    let tags: Vec<String> = groups.iter().map(|(tag, _)| tag.clone()).collect();
    let resource_has_dispatch = groups
        .iter()
        .map(|(tag, _)| {
            api.cli
                .cli_dispatch_groups
                .iter()
                .any(|dispatch| dispatch.resource.to_kebab_case() == tag.to_kebab_case())
        })
        .collect::<Vec<_>>();
    let mut mod_lines = String::new();
    for ((tag, endpoints), (module, enum_name)) in groups.iter().zip(&resources) {
        let resource_name = naming::resource_display_name(tag);
        let dispatch_groups = api
            .cli
            .cli_dispatch_groups
            .iter()
            .filter(|dispatch| dispatch.resource.to_kebab_case() == tag.to_kebab_case())
            .map(|dispatch| commands::ResolvedDispatchGroup {
                group: dispatch,
                members: dispatch
                    .members
                    .iter()
                    .map(|member| {
                        api.endpoints
                            .iter()
                            .find(|endpoint| {
                                endpoint.method == member.method && endpoint.path == member.path
                            })
                            .expect("dispatch members are validated")
                    })
                    .collect(),
            })
            .collect::<Vec<_>>();
        let tokens = commands::render_resource(
            enum_name,
            endpoints,
            &dispatch_groups,
            &catalog,
            &resource_name,
        );
        mod_lines.push_str(&format!("pub mod {module};\n"));
        files.push(GeneratedFile {
            relative_path: format!(".tokyo/src/tokyo/commands/{module}.rs"),
            contents: render_rust_file_from_tokens(tokens),
        });
    }
    files.push(GeneratedFile {
        relative_path: ".tokyo/src/tokyo/commands/mod.rs".to_string(),
        contents: format!("{GENERATED_HEADER}{mod_lines}"),
    });

    let schema_json = schema::render_schema_json(
        &command_name,
        &groups,
        &api.cli,
        &api.schema_components,
        &catalog,
    );
    files.push(GeneratedFile {
        relative_path: ".tokyo/src/cli.rs".to_string(),
        contents: render_rust_file_from_tokens(commands::render_generated_cli_source_tokens(
            &resources,
            &resource_has_dispatch,
            &tags,
            &command_name,
            &schema_json,
        )),
    });

    files
}

fn render_generated_type_tokens(api: &Api, catalog: &TypeCatalog) -> proc_macro2::TokenStream {
    let mut tokens = proc_macro2::TokenStream::new();
    if types::generated_types_use_nullable_wrapper(&api.types) {
        tokens.extend(types::render_nullable_helper());
    }
    for decl in &api.types {
        tokens.extend(types::render_type_declaration(
            decl,
            catalog,
            RENDER_OPTIONS,
        ));
    }
    tokens
}

/// Parses generated tokens as a Rust file and formats them with `prettyplease`
/// — deterministic given the same AST, so golden byte-comparison still works,
/// and doesn't depend on `rustfmt` being installed downstream.
fn render_rust_file_from_tokens(tokens: proc_macro2::TokenStream) -> String {
    let file: syn::File =
        syn::parse2(tokens).expect("generated tokens should parse as a Rust file");
    format!("{GENERATED_HEADER}{}", prettyplease::unparse(&file))
}

fn format_generated_rust_source(source: &str) -> String {
    let file = syn::parse_file(source).expect("generated source should parse as a Rust file");
    format!("{GENERATED_HEADER}{}", prettyplease::unparse(&file))
}
