// Code generated by tokyo-codegen. DO NOT EDIT BY HAND.
// Edit the source API and regenerate instead; hand edits will be overwritten.

#[derive(Debug, clap::Subcommand)]
pub enum DefaultCommand {
    ///[public]
    Download {},
    ///[public]
    GetMixed {},
    ///[public]
    #[command(group(clap::ArgGroup::new("__body_input").required(true).multiple(false)))]
    OptionalJson {
        /// Read the request body from a file, or from stdin with `-`.
        #[arg(long = "body", value_name = "FILE", group = "__body_input")]
        __body_file: Option<String>,
        /// Supply the request body as inline JSON.
        #[arg(long = "body-json", value_name = "JSON", group = "__body_input")]
        __body_json: Option<String>,
        /// Set a request-body field as `path=value`; repeat for more fields.
        #[arg(
            short = 'f',
            long = "field",
            value_name = "PATH=VALUE",
            group = "__body_input"
        )]
        __body_fields: Vec<String>,
    },
    ///[public]
    Submit { #[arg(long = "message")] message: String },
    ///[public]
    ReplaceMultipart { #[arg(long = "file")] file: String },
    ///[public]
    Replace { #[arg(long = "message")] message: String },
}
pub fn dispatch(
    __command: &DefaultCommand,
    __client: &crate::client::Client,
    __output: &crate::output::OutputOptions,
) -> Result<(), crate::error::ClientError> {
    match __command {
        DefaultCommand::Download {} => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = { None };
            let __path = { format!("/download",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Get,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::None,
                    __request_body,
                    Some("application/octet-stream"),
                    None,
                    None,
                )?;
            match __response.status {
                200u16 => {
                    crate::output::print_response_body_as_binary_bytes(
                        &__response.body,
                    )?;
                }
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
        DefaultCommand::GetMixed {} => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = { None };
            let __path = { format!("/mixed",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Get,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::None,
                    __request_body,
                    Some("application/json"),
                    None,
                    Some("application/problem+json"),
                )?;
            match __response.status {
                200u16 => {
                    let __value: crate::tokyo::types::Message = serde_json::from_slice(
                            &__response.body,
                        )
                        .map_err(|error| crate::error::ClientError::Decode(
                            error.to_string(),
                        ))?;
                    crate::output::print_serialized_response(&__value, __output);
                }
                202u16 => {
                    crate::output::print_response_body_as_utf8_text(&__response.body)?;
                }
                204u16 => {}
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
        DefaultCommand::OptionalJson { __body_file, __body_json, __body_fields } => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = {
                (|| -> Result<
                    Option<crate::client::RequestBody>,
                    crate::error::ClientError,
                > {
                    let __request_json = if let Some(__source) = __body_file.as_deref() {
                        let __request_text = crate::client::read_request_body_text(
                            __source,
                        )?;
                        serde_json::from_str(&__request_text)
                            .map_err(|error| {
                                crate::error::ClientError::Decode(
                                    format!("invalid JSON in --body {__source:?}: {error}"),
                                )
                            })?
                    } else if let Some(__source) = __body_json.as_deref() {
                        tokyo_cli_runtime::body::parse_inline_json_request_body(
                            __source,
                        )?
                    } else {
                        tokyo_cli_runtime::body::parse_json_request_body_from_field_assignments(
                            __body_fields,
                        )?
                    };
                    let __request_value: Option<crate::tokyo::types::Message> = serde_json::from_value(
                            __request_json,
                        )
                        .map_err(|error| crate::error::ClientError::Decode(
                            error.to_string(),
                        ))?;
                    Ok(
                        Some(
                            crate::client::RequestBody::Json(
                                serde_json::to_vec(&__request_value)
                                    .expect("a validated value always serializes"),
                            ),
                        ),
                    )
                })()?
            };
            let __path = { format!("/optional-json",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Post,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::None,
                    __request_body,
                    None,
                    Some("application/json"),
                    None,
                )?;
            match __response.status {
                204u16 => {}
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
        DefaultCommand::Submit { message } => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = {
                let __request_value = crate::tokyo::types::Message {
                    message: message.clone(),
                };
                Some(
                    crate::client::RequestBody::Json(
                        serde_json::to_vec(&__request_value)
                            .expect("a validated value always serializes"),
                    ),
                )
            };
            let __path = { format!("/submit",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Post,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::None,
                    __request_body,
                    None,
                    Some("application/json"),
                    None,
                )?;
            match __response.status {
                204u16 => {}
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
        DefaultCommand::ReplaceMultipart { file } => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = {
                let __request_value = crate::tokyo::types::ReplaceMultipartRequest {
                    file: file.clone(),
                };
                Some(
                    crate::client::RequestBody::Multipart(
                        crate::client::build_multipart_request_body(
                            serde_json::to_value(&__request_value)
                                .expect("a validated value always serializes"),
                            &["file"],
                            &[],
                        )?,
                    ),
                )
            };
            let __path = { format!("/multipart-replace",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Put,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::None,
                    __request_body,
                    None,
                    Some("multipart/form-data"),
                    None,
                )?;
            match __response.status {
                204u16 => {}
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
        DefaultCommand::Replace { message } => {
            let __query: Vec<crate::client::QueryParameter> = Vec::new();
            let __headers: Vec<(String, String)> = Vec::new();
            let __request_body = {
                let __request_value = crate::tokyo::types::Message {
                    message: message.clone(),
                };
                Some(
                    crate::client::RequestBody::Json(
                        serde_json::to_vec(&__request_value)
                            .expect("a validated value always serializes"),
                    ),
                )
            };
            let __path = { format!("/replace",) };
            let __target = crate::client::RequestTarget::Relative(&__path);
            let __response = __client
                .request(
                    crate::client::Method::Put,
                    __target,
                    &__query,
                    &__headers,
                    crate::client::AuthMode::None,
                    __request_body,
                    None,
                    Some("application/json"),
                    None,
                )?;
            match __response.status {
                204u16 => {}
                _ => {
                    crate::output::print_untyped_response_body_according_to_content_type(
                        &__response.body,
                        __response.content_type.as_deref(),
                        __output,
                    )?
                }
            }
            Ok(())
        }
    }
}
pub fn delete_by_id(_id: &str) -> Option<DefaultCommand> {
    None
}
